### ISSUE TITLE
Korean translation (Closed)

### ISSUE THREAD

**Issue by septemberstokii** [ncase/mental-health#6]
~~I'm working on a Korean translation~~ (Closed)

**Comment by ncase** [comment]
Thank you for taking on this challenge! :) 

>  is it okay to add them to our nation's welfare institutions using quotations?

Yes, of course! We both want this to be helpful to the actual people in Korea who will be reading your Korean translation 👍

**Comment by septemberstokii** [comment]
@ncase Sorry. i'm try this challenge but translation is yet unfortunately some hard. close this issue. sry.
